### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by choucavalier** [toogy/hitchhike#1]
##### Views
- [ ] Log in, Register, Change Password
- [ ] AJAX vote up/down
- [ ] E-mail subscribe/unsubscribe
- [ ] Validate/Unvalidate answer
##### Stuff
- [x] Markdown/MathJax widget
- [ ] Limit rate on views ([django-brake](https://github.com/gmcquillan/django-brake))
- [ ] Filter questions by tag
- [ ] Filter questions opened by current user
- [ ] [django-avatar](https://github.com/grantmcconnaughey/django-avatar)
- [ ] Search questions and answers
#### Optional
- [ ] Filter questions by time _(today, a week, a month, all time...)_
- [ ] Filter questions by answered
- [ ] Support cool icons ([fontello](http://fontello.com/))
- [x] Support mobile devices
- [ ] Make the delete question confirmation a popup instead of a full page (UX)

We take any suggestion
